package testcases

import "uniq/options"

type TestCase struct {
	Name     string
	Input    []string
	Expected []string
	Options  options.Options
}

var TestsNoParemeters []TestCase = []TestCase{
	{
		Name: "noParameters",
		Input: []string{
			"Today we gathered moss for my uncle's wedding.",
			"Today we gathered moss for my uncle's wedding.",
			"Today we gathered moss for my uncle's wedding.",
			"hello",
			"Today we gathered moss for my uncle's wedding.",
			"",
			" ",
			"hello",
			"hello",
			"hi",
			"hello",
			"Today we gathered moss for my uncle's wedding.",
		},
		Expected: []string{
			"Today we gathered moss for my uncle's wedding.",
			"hello",
			"Today we gathered moss for my uncle's wedding.",
			"",
			" ",
			"hello",
			"hi",
			"hello",
			"Today we gathered moss for my uncle's wedding.",
		},
	},
	{
		Name: "noParameters",
		Input: []string{
			"a",
			"a",
			"a ",
			"a    ",
			"b",
			"b",
			"a",
			"a",
			"	",
			"	",
			" ",
			"a",
		},
		Expected: []string{
			"a",
			"a ",
			"a    ",
			"b",
			"a",
			"	",
			" ",
			"a",
		},
	},
}

var Tests_c_Flag []TestCase = []TestCase{
	{
		Name: "-c flag",
		Input: []string{
			"",
			" ",
			"He learned the important lesson that a picnic at the beach on a windy day is a bad idea.",
			"He learned the important lesson that a picnic at the beach on a windy day is a bad idea.",
			"",
			"The book is in front of the table.",
			"The book is in front of the table.",
			"The book is in front of the table.",
			"The book is in front of the table.",
			"The book is in front of the table.",
			"",
			"",
			"",
			"",
			" ",
			" ",
			" ",
			" ",
			"hello",
			"hi",
			"hello",
			"hi",
			"hello",
			"",
		},
		Expected: []string{
			"    1 ",
			"    1  ",
			"    2 He learned the important lesson that a picnic at the beach on a windy day is a bad idea.",
			"    1 ",
			"    5 The book is in front of the table.",
			"    4 ",
			"    4  ",
			"    1 hello",
			"    1 hi",
			"    1 hello",
			"    1 hi",
			"    1 hello",
			"    1 ",
		},
		Options: options.Options{C: true},
	},
	{
		Name: "-c flag",
		Input: []string{
			"alpha beta gamma",
			"alpha beta gamma",
			"ALPHA beta gamma",
			"alpha  beta gamma",
			"alpha beta gamma",
			"alpha beta gamma",
			"",
			"",
			" ",
			"",
			"omega",
			"omega",
		},
		Expected: []string{
			"    2 alpha beta gamma",
			"    1 ALPHA beta gamma",
			"    1 alpha  beta gamma",
			"    2 alpha beta gamma",
			"    2 ",
			"    1  ",
			"    1 ",
			"    2 omega",
		},
		Options: options.Options{C: true},
	},
	{
		Name: "-c flag",
		Input: []string{
			"line",
			"line",
			"line",
			"line ",
			"line ",
			"   ",
			"   ",
			"line",
			"line",
		},
		Expected: []string{
			"    3 line",
			"    2 line ",
			"    2    ",
			"    2 line",
		},
		Options: options.Options{C: true},
	},
	{
		Name: "-c flag",
		Input: []string{
			"       ",
			"       ",
			"	",
			" ",
			"single",
			"single",
			"	 ",
		},
		Expected: []string{
			"    2        ",
			"    1 	",
			"    1  ",
			"    2 single",
			"    1 	 ",
		},
		Options: options.Options{C: true},
	},
}

var Tests_d_Flag []TestCase = []TestCase{
	{
		Name: "-d flag",
		Input: []string{
			"",
			" ",
			"He learned the important lesson that a picnic at the beach on a windy day is a bad idea.",
			"He learned the important lesson that a picnic at the beach on a windy day is a bad idea.",
			"",
			"The book is in front of the table.",
			"The book is in front of the table.",
			"The book is in front of the table.",
			"The book is in front of the table.",
			"The book is in front of the table.",
			"",
			"",
			"",
			"",
			" ",
			" ",
			" ",
			" ",
			"hello",
			"hi",
			"hello",
			"hi",
			"hello",
			"",
		},
		Expected: []string{
			"He learned the important lesson that a picnic at the beach on a windy day is a bad idea.",
			"The book is in front of the table.",
			"",
			" ",
		},
		Options: options.Options{D: true},
	},
	{
		Name: "-d flag",
		Input: []string{
			"one",
			"one",
			"two",
			"three",
			"two",
			"two",
			"two",
			"One",
			"one",
		},
		Expected: []string{
			"one",
			"two",
		},
		Options: options.Options{D: true},
	},
	{
		Name: "-d flag",
		Input: []string{
			"x",
			"x",
			"y",
			"z",
			"z",
			"z",
			"y",
			"y",
			"x",
			"x",
		},
		Expected: []string{
			"x",
			"z",
			"y",
			"x",
		},
		Options: options.Options{D: true},
	},
}

var Tests_u_Flag []TestCase = []TestCase{
	{
		Name: "-u flag",
		Input: []string{
			"",
			" ",
			"He learned the important lesson that a picnic at the beach on a windy day is a bad idea.",
			"He learned the important lesson that a picnic at the beach on a windy day is a bad idea.",
			"",
			"The book is in front of the table.",
			"The book is in front of the table.",
			"The book is in front of the table.",
			"The book is in front of the table.",
			"The book is in front of the table.",
			"",
			"",
			"",
			"",
			" ",
			" ",
			" ",
			" ",
			"hello",
			"hi",
			"hello",
			"hi",
			"hello",
			"",
		},
		Expected: []string{
			"",
			" ",
			"",
			"hello",
			"hi",
			"hello",
			"hi",
			"hello",
			"",
		},
		Options: options.Options{U: true},
	},
	{
		Name: "-u flag",
		Input: []string{
			"first",
			"second",
			"second",
			"third",
			"fourth",
			"fourth",
			"fifth",
			"second",
		},
		Expected: []string{
			"first",
			"third",
			"fifth",
			"second",
		},
		Options: options.Options{U: true},
	},
	{
		Name: "-u flag",
		Input: []string{
			"apple",
			"banana",
			"apple",
			"banana",
			"cherry",
			"cherry",
			"apple",
		},
		Expected: []string{
			"apple",
			"banana",
			"apple",
			"banana",
			"apple",
		},
		Options: options.Options{U: true},
	},
}

var Tests_i_Flag []TestCase = []TestCase{
	{
		Name: "-i flag",
		Input: []string{
			"",
			" ",
			"he LeARneD The iMPORtANt LessON tHaT a Picnic At tHE BEaCh on a WINDY day iS A bAD IDEa.",
			"he learnED tHE ImPoRtant lEsSON tHaT A piCNic aT tHE beACH on a windY dAY Is a bad IdEa.",
			"",
			"THe BoOk Is iN FroNt Of tHe TABlE.",
			"THe booK is in frOnt of tHE TabLe.",
			"tHE BOoK is in FRoNT oF tHe TAbLe.",
			"the boOk is iN frONT Of tHe tAblE.",
			"tHE BoOk IS iN front OF the tablE.",
			"",
			"i LIked THeiR fiRst tWO albUmS BuT CHAnged my Mind aFTeR THat CHaRITy gIG.",
			" ",
			"hELLO",
			"hELLO",
			"hi",
			"hello",
			"i liked THEiR fIrst TWO aLBuMS BUt cHANgED mY miND afteR thAt cHARity gig.",
			" ",
			" ",
			"hEllO",
			"hi",
			"HelLO",
			"hI",
			"hELlo",
			"",
		},
		Expected: []string{
			"",
			" ",
			"he LeARneD The iMPORtANt LessON tHaT a Picnic At tHE BEaCh on a WINDY day iS A bAD IDEa.",
			"",
			"THe BoOk Is iN FroNt Of tHe TABlE.",
			"",
			"i LIked THeiR fiRst tWO albUmS BuT CHAnged my Mind aFTeR THat CHaRITy gIG.",
			" ",
			"hELLO",
			"hi",
			"hello",
			"i liked THEiR fIrst TWO aLBuMS BUt cHANgED mY miND afteR thAt cHARity gig.",
			" ",
			"hEllO",
			"hi",
			"HelLO",
			"hI",
			"hELlo",
			"",
		},
		Options: options.Options{I: true},
	},
}

var Tests_f_Flag []TestCase = []TestCase{
	{
		Name: "-f flag",
		Input: []string{
			"12.03.25 Today we gathered moss for my uncle's wedding.",
			"13.03.25 Today we gathered moss for my uncle's wedding.",
			"14.03.25 Today we gathered moss for my uncle's wedding.",
			"15.03.25 hello",
			"16.03.25 Today we gathered moss for my uncle's wedding.",
			"17.03.25 ",
			"18.03.25  ",
			"19.03.25 hello",
			"20.03.25 hello",
			"21.03.25 hi",
			"22.03.25 hello",
			"23.03.25 Today we gathered moss for my uncle's wedding.",
		},
		Expected: []string{
			"12.03.25 Today we gathered moss for my uncle's wedding.",
			"15.03.25 hello",
			"16.03.25 Today we gathered moss for my uncle's wedding.",
			"17.03.25 ",
			"18.03.25  ",
			"19.03.25 hello",
			"21.03.25 hi",
			"22.03.25 hello",
			"23.03.25 Today we gathered moss for my uncle's wedding.",
		},
		Options: options.Options{F: 1},
	},
	{
		Name: "-f flag",
		Input: []string{
			"2026-02-17 INFO started process A",
			"2026-02-17 INFO started process A",
			"2026-02-17 DEBUG started process A",
			"2026-02-17 INFO started process B",
			"2026-02-18 INFO started process A",
			"INFO started process A",
		},
		Expected: []string{
			"2026-02-17 INFO started process A",
			"2026-02-17 DEBUG started process A",
			"2026-02-17 INFO started process B",
			"2026-02-18 INFO started process A",
			"INFO started process A",
		},
		Options: options.Options{F: 1},
	},
	{
		Name: "-f flag",
		Input: []string{
			"A BB C",
			"UO BBB C",
			"XYZ 11Y Z",
			"OOO 9 Z",
		},
		Expected: []string{
			"A BB C",
			"XYZ 11Y Z",
		},
		Options: options.Options{F: 2},
	},
}

var Tests_s_Flag []TestCase = []TestCase{
	{
		Name: "-s flag",
		Input: []string{
			"ABCfoobar",
			"ABDfoobar",
			"ABEfoobar",
			"ABCfoobar",
			"XYZfoobar",
			"XYafoobar",
		},
		Expected: []string{
			"ABCfoobar",
		},
		Options: options.Options{S: 3},
	},
}
